<?php

session_start();

include('db_config.php');

// Your ip address
$ipAddress = '192.168.1.117';

function CallAPI($method, $url, $data = false)
{
    $curl = curl_init();

    switch ($method)
    {
        case "POST":
            curl_setopt($curl, CURLOPT_POST, 1);

            if ($data)
                curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
            break;
        case "PUT":
            curl_setopt($curl, CURLOPT_PUT, 1);
            break;
        default:
            if ($data)
                $url = sprintf("%s?%s", $url, http_build_query($data));
    }

    // Optional Authentication:
    curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($curl, CURLOPT_USERPWD, "username:password");

    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

    $result = curl_exec($curl);
    echo curl_error($curl);
    curl_close($curl);

    return $result;
}

function sendPost($url, $data) {
    $curl = curl_init($url);
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

    $headers = array(
        "Accept: application/json",
        "Content-Type: application/json; charset=utf-8",
    );
    curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

    curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

    $resp = curl_exec($curl);
    curl_close($curl);
    return $resp;
}

function generateRandom() {
    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $n=32;
    $randomString = '';

    for ($i = 0; $i < $n; $i++) {
        $index = rand(0, strlen($characters) - 1);
        $randomString .= $characters[$index];
    }
    return $randomString;
}

function randomByte() {
    $bytes = '0123456789abcdef';
    $index = rand(0, strlen($bytes) - 1);
    return $bytes[$index];
}

function challengeSolution($secret, $randomApi) {
    $challenge = "$secret$randomApi";
    return hash("sha256", $challenge, false);
}


// Get username from api
$usernameGet = CallAPI("GET", "http://$ipAddress:5000/login");
$usernameJson = json_decode($usernameGet);
$username = $usernameJson->{'username'};
if ($username == '') {
    CallAPI("GET", "http://$ipAddress:5000/shutdown");
    $_SESSION['not_auth'] = true;
	header('Location: index.php');
	exit();
}

$salt = generateRandom();
$iterations = 100000;

// Fetch password from database. Idealy this would be in the database. 
// For quick testing we implemented the password coding here, the algorithm would still work
$query = "SELECT password FROM Client WHERE username='$username'";
$pass= mysqli_query($connection, $query);
$result= mysqli_query($connection, $query);
$row = mysqli_fetch_row($result);
$password = $row[0];
$password = utf8_encode($password);
// calculate secret
$secret = hash_pbkdf2("sha256", $password, $salt, $iterations, 64, false);

// Send iterations and salt to api. Receive random generated by api
$data = new stdClass();
$data->salt = $salt;
$data->iter = $iterations;
$dataSent = json_encode($data, JSON_UNESCAPED_UNICODE);
$randomApiJson = json_decode(sendPost("http://$ipAddress:5000/secretInfo", $dataSent));
$randomApi = $randomApiJson->{'random'};

$flag = true;

for ($i = 0; $i < strlen($secret); $i++) {
    // Send and receive byte
    if ($flag == true) {
        if ($i == 0) {
            $solutionApi = (challengeSolution($secret, $randomApi));
            $byteOut = $solutionApi{$i};
        } else {
            $solutionServ = (challengeSolution($secret, $randomServ));
            if ($solutionServ{$i-1} == $byteIn) {
                $solutionApi = (challengeSolution($secret, $randomApi));
                $byteOut = $solutionApi{$i};
            } else {
                $flag = false;
                $byteOut = randomByte();
            }
        }
    } else {
        $byteOut = randomByte();
    }
    $randomServ = generateRandom();
    $dataOut = new stdClass();
    $dataOut->index = $i;
    $dataOut->byte = $byteOut;
    $dataOut->rand = $randomServ;
    $dataOutJson = json_encode($dataOut, JSON_UNESCAPED_UNICODE);
    $dataInJson = json_decode(sendPost("http://$ipAddress:5000/sendByte", $dataOutJson));
    $byteIn = $dataInJson->{'byte'};
    $randomApi = $dataInJson->{'rand'};
}

if ($flag == true) {
    CallAPI("GET", "http://$ipAddress:5000/shutdown");
    $_SESSION['username'] = $username;
	header('Location: main.php');
	exit();
} else {
    CallAPI("GET", "http://$ipAddress:5000/shutdown");
    $_SESSION['not_auth'] = true;
	header('Location: index.php');
	exit();
}
?>